server:
  port: 8081
spring:
  application:
    name: service-code
  cloud:
    config:
      uri: http://localhost:9006
      name: ${spring.application.name}
      profile: dev
      label: main
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://CloudEurekaServerA:8761/eureka, http://CloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}/${spring.application.name}:${server.port}:@project.version@
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  client:
    config:
      lagou-service-email:
        connectTimeout: 15000
        readTimeout: 15000