server:
  port: 8081
spring:
  application:
    name: service-code
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.155.46.98:3306/login-test?useUnicode=true&characterEncoding=utf8
    username: test
    password: test@dev
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://139.155.46.98:8761/eureka,http://139.155.2.145:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}/${spring.application.name}:${server.port}:@project.version@
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  client:
    config:
      connectTimeout: 15000
      readTimeout: 15000
